### ISSUE TITLE
Create a single build command for both Go and UI

### ISSUE THREAD

**Issue by friendly-developer** [KingAkeem/TorBotApp#2]
Link for the discussion https://github.com/KingAkeem/goTor/issues/12

**Comment by KingAkeem** [comment]
Insight: Currently there are two build scripts for the UI and Server. 
UI: https://github.com/KingAkeem/TorBotApp/blob/master/dev/run_gui.sh
Server: https://github.com/KingAkeem/TorBotApp/blob/master/dev/run_server.sh

**Comment by friendly-developer** [comment]
Planning to refactor package.json to add a predevelop command which triggers go build first and then runs yarn start. 

this way if the predevelop command fails then no need to continue with the UI build

**Comment by KingAkeem** [comment]
Nice, I like the idea. Can't wait to check out the PR

**Comment by KingAkeem** [comment]
This PR will no longer be needed since the Golang code has been removed. The app is now written in TypeScript
